# Site settings
title: Fizjoterapia Gdańsk
description: "Gabinet fizjoterapii, Gdańsk, trójmiasto. Paweł Jendrzejewski"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: img/logo3.png

# Hero
hero: 
    hero_img: omnie.jpg
    hero_title: Fizjoterapia Gdańsk
    hero_description: Paweł Jendrzejewski

# Contact info
contact:
    phone: +48 792 512 907
    email: pawel.jendrzejewski@gmail.com
    address: ul. Miszewskiego 12/13 <br> Gdańsk, 80-239 <br> (budynek Zakładu Doskonalenia Zawodowego) <br><br> ul. Juliusza Słowackiego 4 <br> Gdańsk, 80-257 <br> (teren klubu Fitness Spójnia)
# Opening hours
monday_friday: 8:00 – 22:00
saturday: 8:00 – 17:00
sunday: 8:00 – 17:00
# Testimonials
testimonials:
    testimonials_img: hero.jpg

# Map
map:
    zoom: 17
    address: Miszewskiego 12/13, Gdańsk, Poland
    address_details: img/logo2.png

# Social settings
facebook: https://www.facebook.com/gdanskfizjoterapia/

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
